--require("plugin")
require("basic")
--require("lsp/setup")
--require("lsp/lua")
--require("lsp/ccls")
--require("lsp/ltex")
require("keybindings")

require("plugin-lazy")
require("plugin-config/coc")
require("plugin-config/nvim-treesitter")
require("plugin-config/indent-blankline")
require("plugin-config/nvim-tree")
require("plugin-config/telescope")
require("plugin-config/lualine")
require("plugin-config/null-ls")
require("plugin-config/vista")
--require("plugin-config/cmp")
require("plugin-config/vim-tex")

require("colorscheme")

require("plugin-config/aerial")
require("plugin-config/blamer")
require("plugin-config/bufferline")
